-- Run this once in Supabase SQL Editor.
-- This table stores one complete ballot per authenticated voter.
create table if not exists public.vote_ballots (
  id bigint generated by default as identity primary key,
  election_id bigint not null references public.elections(id) on delete cascade,
  voter_id uuid not null references auth.users(id) on delete cascade,
  selections jsonb not null,
  created_at timestamptz not null default now(),
  unique (election_id, voter_id)
);

alter table public.elections add column if not exists start_date date;
alter table public.elections add column if not exists end_date date;
alter table public.elections add column if not exists deadline time;
alter table public.elections add column if not exists eligible_voters integer default 0;
alter table public.candidates add column if not exists initials text;
alter table public.candidates add column if not exists description text;

update public.elections
set start_date = coalesce(start_date, current_date),
    end_date = coalesce(end_date, current_date + 7),
    deadline = coalesce(deadline, '23:59'::time),
    eligible_voters = coalesce(eligible_voters, 100)
where id = 1;

alter table public.vote_ballots enable row level security;

revoke all on public.vote_ballots from anon;
revoke all on public.vote_ballots from authenticated;

drop policy if exists "authenticated users submit own ballot"
on public.vote_ballots;

create policy "authenticated users submit own ballot"
on public.vote_ballots
for insert
to authenticated
with check (
  voter_id = (select auth.uid())
  and jsonb_typeof(selections) = 'object'
  and exists (
    select 1
    from public.elections
    where elections.id = vote_ballots.election_id
      and elections.status = 'active'
  )
);

drop function if exists public.get_election_results(bigint);

create function public.get_election_results(requested_election_id bigint)
returns table (candidate_position text, candidate_name text, vote_count bigint)
language sql
security definer
set search_path = public
as $$
  select
    entries.key as candidate_position,
    entries.value as candidate_name,
    count(*)::bigint as vote_count
  from public.vote_ballots ballots
  cross join lateral jsonb_each_text(ballots.selections) entries
  where ballots.election_id = requested_election_id
    and exists (
      select 1
      from public.elections
      where elections.id = ballots.election_id
        and elections.status = 'closed'
    )
  group by entries.key, entries.value
  order by entries.key, count(*) desc, entries.value;
$$;

revoke all on function public.get_election_results(bigint) from public;
grant execute on function public.get_election_results(bigint) to authenticated;

-- Only users whose server-managed app_metadata says admin may manage election data.
drop policy if exists "admins manage elections"
on public.elections;

create policy "admins manage elections"
on public.elections
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins manage candidates"
on public.candidates;

create policy "admins manage candidates"
on public.candidates
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create or replace function public.get_admin_results(requested_election_id bigint)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total_votes', (
      select count(*)
      from public.vote_ballots
      where election_id = requested_election_id
    ),
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'position', grouped_entries.position,
        'candidate_name', grouped_entries.candidate_name,
        'vote_count', grouped_entries.vote_count
      ))
      from (
        select
          entries_inner.key as position,
          entries_inner.value as candidate_name,
          count(*)::bigint as vote_count
        from public.vote_ballots inner_ballots
        cross join lateral jsonb_each_text(inner_ballots.selections) entries_inner
        where inner_ballots.election_id = requested_election_id
        group by entries_inner.key, entries_inner.value
      ) grouped_entries
    ), '[]'::jsonb)
  )
  where (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin';
$$;

revoke all on function public.get_admin_results(bigint) from public;
grant execute on function public.get_admin_results(bigint) to authenticated;
